Backport all fixes in main branch to 0.1.x (#33)
* version bump 0.2.0

* Version bump 1.0.0

* Add timeout to exec(npm ls) call (#15)

* Update package.json

* version bump 1.0.2

* Readme update

* Request timeout (#16)

* Request timeout

* version bump 1.0.3

* Intermediate package opt out (#19)

* version bump 1.0.4

* Relicense as Apache-2.0 (#20)

* Update License file to full Apache-2.0 text

* version bump 1.0.5

* Update link

* Disable scarf-js analytics when yarn is the installing package manager (#21)

* Hash package names and versions of grandparent and root (#23)

* version bump 1.0.6

* Update README download badge link

* Readme updates

* Set maxBuffer for Dependency tree output (#25)

Tried to use scarf for my project botium-bindings.
I am receiving this error message on _npm install_:

    SyntaxError: Unexpected end of JSON input
        at JSON.parse (<anonymous>)
        at /home/ftreml/dev/botium-bindings/node_modules/@scarf/scarf/report.js:122:27
        at ChildProcess.exithandler (child_process.js:301:5)
        at ChildProcess.emit (events.js:198:13)
        at maybeClose (internal/child_process.js:982:16)
        at Process.ChildProcess._handle.onexit (internal/child_process.js:259:5)

Seems that the stdout stream for _npm -ls_ (dependency tree) is truncated. 

Possible fix: add _maxBuffer_  to child process options.

* update to link to new blogpost

* Bump lodash from 4.17.15 to 4.17.19 (#28)

Bumps [lodash](https://github.com/lodash/lodash) from 4.17.15 to 4.17.19.
- [Release notes](https://github.com/lodash/lodash/releases)
- [Commits](https://github.com/lodash/lodash/compare/4.17.15...4.17.19)

Signed-off-by: dependabot[bot] <support@github.com>

Co-authored-by: dependabot[bot] <49699333+dependabot[bot]@users.noreply.github.com>

* Enable analytics when target package has no parent.  (#27)

* version bump 1.1.0

* Added nix files

* Update README.md

* add nix to linguist ignore

* Used like for missing verb. (#30)

* License copyright notice

* delete trailing whitespace

* bump version of 0.1.x branch to 0.1.8

* fixup, duplicate const

Co-authored-by: Botium <florian.treml@botium.at>
Co-authored-by: dependabot[bot] <49699333+dependabot[bot]@users.noreply.github.com>
Co-authored-by: Tim Dysinger <tim@scarf.sh>
Co-authored-by: Tim Dysinger <tim@dysinger.net>
Co-authored-by: Phil de Joux <philderbeast@gmail.com>